# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: mpgap-3.2

channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda

dependencies:
  ## python pip dependencies
  - pip
  - pip:
    - setuptools
    - matplotlib>=1.3.1
    - medaka>=1.4
  
  ## anaconda main channel
  - main::openssl
  
  ## anaconda packages
  - anaconda::python=3.6
  - anaconda::numpy                               # for medaka through pip
  
  ## conda-forge packages
  - conda-forge::gcc
  - conda-forge::hdf5=1.10                        # nanopolish is not loading it
  - conda-forge::hdf5-static                      # nanopolish is not loading it
  - conda-forge::zlib                             # for nanopolish

  ## bioconda packages
  - bioconda::htslib
  - bioconda::blast=2.12.0
  - bioconda::racon=1.4.20
  - bioconda::pilon=1.24
  - bioconda::canu=2.2
  - bioconda::spades=3.15.3
  - bioconda::unicycler=0.5.0
  - bioconda::mummer
  - bioconda::bowtie2
  - bioconda::freebayes
  - bioconda::minimap2=2.22
  - bioconda::nanopolish=0.13.2
  - bioconda::pbgcpp=2.0.2
  - bioconda::pbmm2=1.7.0
  - bioconda::flye=2.9
  - bioconda::quast=5.2.0
  - bioconda::miniasm=0.3_r179
  - bioconda::seqtk=1.3
  - bioconda::shovill=1.1.0
  - bioconda::haslr=0.8a1
  - bioconda::raven-assembler=1.6.1
  - bioconda::multiqc=1.11
  - bioconda::csvtk=0.23.0
  - bioconda::wtdbg=2.5

  # for medaka > 1.4
  - bioconda::samtools>=1.11
  - bioconda::tabix>=1.11
  - bioconda::bcftools>=1.11
  - bioconda::mappy