name: Testing long-reads / docker (ONT) from PR
on:
  pull_request:
    branches: [ master, dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  run_nextflow:
    name: Run pipeline for the upcoming PR
    runs-on: macos-latest
    
    steps:

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
      
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      
      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      - name: Run tests for long-reads (ont)
        run: |
          nextflow run main.nf -profile docker,test,lreads,ont --max_memory '6.GB' --max_cpus 2 --skip_flye
          rm -r work .nextflow*
      
      - name: View results
        run: |
          sudo apt-get install -y tree
          tree lreads_test_ont
