# This workflow set's up an automated execution for testing the code when a new PR is created
# It uses the head branch name to trigger the execution of the new module or subworkflow ...
#
# For example, if I just created a module for roary, I should name the new branch as roary
# then, this workflow will run: nextflow run fmalmeida/bacannot-compare --roary (the head branch name) [blah blah blah]

name: Testing nanopore / singularity from PR
on:
  pull_request:
    branches: master
    types: [ opened, synchronize, reopened ]

jobs:
  run_nextflow:
    name: Run pipeline for the upcoming PR
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
      
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      
      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      
      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      
      - name: Run tests for nanopore
        run: |
          wget https://github.com/fmalmeida/test_datasets/raw/main/ecoli_ont_15X.fastq.gz
          nextflow run main.nf \
            -profile singularity \
            --max_cpus 2 \
            --output TEST_DIR \
            --nanopore_fastq "ecoli_ont_15X.fastq.gz"
          rm -r work .nextflow*
      
      - name: View results
        run: |
          sudo apt-get install -y tree
          tree TEST_DIR
